"use client";

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { JSX } from "react";
import "@authdog/react-elements/styles.css";
import { Button, Navbar } from "@authdog/react-elements";
import { useRouter } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Nextjs - Demo",
//   description: "Generated by create turbo",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
      const router = useRouter();

  return (
    <html lang="en">
        <body className={inter.className}>
          <div className="min-h-screen flex flex-col">
            <Navbar
              logoText="Acme Inc"
              items={[
                { title: "Home", href: "/" },
              ]}
              user={{
                name: "Sarah Johnson",
                email: "sarah@acme.com",
                image: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
              }}
              onNavItemClick={(href) => router.push(href)}
              onProfileSelected={() => router.push("/profile")}
              onLogout={() => console.log("Logging out...")}
            >
              <Button variant="ghost" size="sm">
                Docs
              </Button>
              <Button size="sm">Get Started</Button>
            </Navbar>
            <main className="flex-1">
              {children}
            </main>
          </div>
      </body>
    </html>
  );
}
