// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/logout": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/profile" | "/logout";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/logout.ts": {
    id: "routes/logout";
    page: "/logout";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/logout": typeof import("./app/routes/logout.ts");
};