name: cd-next-app-deploy

on:
  push:
    branches:
      - main
    paths:
      - apps/nextjs/**
      - .github/workflows/cd-next-app-demo.yml
  workflow_dispatch:

env:
  # codebase
  STORE_PATH: ~/.pnpm-store
  ENVFILE_CONSOLE: apps/nextjs/.env
  SCOPE_VERCEL: david-barrats-projects-b894a911
  PROJECT_VERCEL: nextjs-demo

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v4
        with:
          version: 9.0.0

      # - name: Use taobao registry
      #   run: npm config set registry https://registry.npmmirror.com/

      - name: Setup PNPM store path
        run: pnpm config set store-dir ${{ env.STORE_PATH }}

      - name: Setup Pnpm Cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-cache-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build workspace packages
        run: |
          make build
      
      - name: Install latest dependencies in nextjs
        run: |
          (cd apps/nextjs; pnpm add @authdog/nextjs-app@latest)

      # - name: Build Next.js app
      #   run: |
      #     (cd apps/nextjs;pnpm run build)

      - name: Ship NextJS demo
        run: |
          npx vercel deploy \
            --cwd apps/nextjs \
            --token ${{ secrets.VERCEL_CD_TOKEN }} \
            --scope ${{ env.SCOPE_VERCEL }} \
            --name ${{ env.PROJECT_VERCEL }} \
            --force \
            --yes \
            --prod \
            --build-env NODE_PATH=$PWD/node_modules