name: cd-packages-publish

on:
  push:
    branches:
      - main
    paths:
      - packages/**
  workflow_dispatch:

env:
  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
  GH_AUTOMATION_TOKEN: ${{ secrets.GH_AUTOMATION_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        with:
          version: 9.0.0

      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Configure NPM token
        run: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc

      - run: pnpm install

      # - name: Create Release Pull Request
      #   id: changesets-version
      #   uses: changesets/action@v1
      #   with:
      #     version: true
      #   env:
      #     GITHUB_TOKEN: ${{ env.GH_AUTOMATION_TOKEN }}
      #     NPM_TOKEN: ${{ env.NPM_AUTOMATION_TOKEN }}
      #   if: github.ref != 'refs/heads/main'

      # - name: Publish packages
      #   id: changesets-publish
      #   uses: changesets/action@v1
      #   with:
      #     publish: true
      #   env:
      #     GITHUB_TOKEN: ${{ env.GH_AUTOMATION_TOKEN }}
      #     NPM_TOKEN: ${{ env.NPM_AUTOMATION_TOKEN }}
      #   if: github.ref == 'refs/heads/main'

      - name: Create Release Pull Request
        id: changesets-version
        uses: changesets/action@v1
        with:
          version: |
            pnpm generate-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GH_AUTOMATION_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
        if: github.ref != 'refs/heads/main'

      - name: Publish packages
        id: changesets-publish
        uses: changesets/action@v1
        with:
          publish: |
            pnpm publish-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_AUTOMATION_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
        if: github.ref == 'refs/heads/main'