name: packages-publish

on:
  push:
    branches:
      - main
    paths:
      - packages/**
  workflow_dispatch:

env:
  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
  GH_AUTOMATION_TOKEN: ${{ secrets.GH_AUTOMATION_TOKEN }}

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - uses: dbrrt/setup-moon@v1.0.0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.14

      - uses: actions/cache@v6
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-cache-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-cache-

      - name: Configure NPM token
        run: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc

      - run: bun install --frozen-lockfile

      # - name: Create Release Pull Request
      #   id: changesets-version
      #   uses: changesets/action@v1
      #   with:
      #     version: true
      #   env:
      #     GITHUB_TOKEN: ${{ env.GH_AUTOMATION_TOKEN }}
      #     NPM_TOKEN: ${{ env.NPM_AUTOMATION_TOKEN }}
      #   if: github.ref != 'refs/heads/main'

      # - name: Publish packages
      #   id: changesets-publish
      #   uses: changesets/action@v1
      #   with:
      #     publish: true
      #   env:
      #     GITHUB_TOKEN: ${{ env.GH_AUTOMATION_TOKEN }}
      #     NPM_TOKEN: ${{ env.NPM_AUTOMATION_TOKEN }}
      #   if: github.ref == 'refs/heads/main'

      - name: Create Release Pull Request
        id: changesets-version
        uses: changesets/action@v1
        with:
          version: |
            bun run generate-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GH_AUTOMATION_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
        if: github.ref != 'refs/heads/main'

      - name: Publish packages
        id: changesets-publish
        uses: changesets/action@v1
        with:
          publish: |
            bun run publish-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_AUTOMATION_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
        if: github.ref == 'refs/heads/main'