name: react-docs-deploy

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - packages/react-elements/**
  #     - .github/workflows/react-docs-deploy.yml

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: 07cdb3d8cc681313ba8b3d915e35cd81
  BUN_CACHE_PATH: ~/.bun/install/cache
  # ENVFILE_CONSOLE: examples/nextjs-app/.env
  # SCOPE_VERCEL: david-barrats-projects-b894a911
  # PROJECT_VERCEL: react-elements

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.1

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.BUN_CACHE_PATH }}
          key: ${{ runner.os }}-bun-cache-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-cache-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Deploy Storybook
        run: |
          (cd packages/react-elements; \
            CLOUDFLARE_ACCOUNT_ID="${{ env.CLOUDFLARE_ACCOUNT_ID }}" \
            CLOUDFLARE_API_TOKEN="${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            NODE_ENV=prod \
            bun run deploy-docs
          )